blank_issues_enabled: false
contact_links:
    - name: Bug Reports
      url: https://tatsumoto.neocities.org/blog/join-our-community
      about: This issue tracker is for developers. Please report any bugs you encounter over in the chats, and they will be triaged there.

    - name: Questions/Support
      url: https://tatsumoto.neocities.org/blog/join-our-community
      about: If you have a question or need support, please post in the community chats.

    - name: Feature Requests/Suggestions
      url: https://tatsumoto.neocities.org/blog/join-our-community
      about: Please post suggestions and feature requests in our chat.
